[package]
name = "dag_calculation_rust"
version = "0.1.0"
authors = ["maksutovaynur <maksutov_aynur@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
